### ISSUE TITLE
Resuming a partial pipeline

### ISSUE THREAD

**Issue by joezuntz** [LSSTDESC/ceci#10]
We'd like to be able to robustly resume a partially run pipeline, skipping stages that were completed the first time.

The current `resume` option only checks whether the file exists, which does not work if the file is partially completed - the pipeline.

@yadudoc (sorry, don't know Kyle's github name to include him too)  - does Parsl have any specific features (or planned features) for re-running pipelines?  Or can you suggest approaches to this?

**Comment by yadudoc** [comment]
Please scratch the previous comment.

I believe that there is a misunderstanding here about the completion state of parsl apps. Parsl calls an app "done" only when a non-zero exit code is returned and all the specified output files are available. If you are writing checkpoints, and start a rerun, we don't look at the files but at the checkpoint records to determine what apps completed and can be skipped. For all apps that did not complete/failed, parsl re-launches them. At the point of relaunches any app that has internal mechanisms to checkpoint and resume can use it's checkpoint files to resume.

**Comment by joezuntz** [comment]
I've added a feature to ceci to deal with the partial completion issue - files are now only moved to their final location once the process finishes.  This doesn't help with checkpointing in the middle of tasks, but that is significantly more complicated and task-specific, so I think this is useful for now.
