### ISSUE TITLE
Add support for containers

### ISSUE THREAD

**Issue by EiffL** [LSSTDESC/ceci#11]
Given the heterogeneous nature of the DESC pipelines, I anticipate that we will soon be running into a major hurdle to keep track of all the software dependencies of all the pipeline stages. One option is to execute the pipeline in Docker containers, leaving it the responsibility of the pipeline designers to provide a container that can execute their codes. The benefits of this approach are the following:
  - Reproducibility,  thanks to containers providing a versioned software environment
  - Portability, thanks to containerization

After talking with @yadudoc today, it sounds like `parsl` with conveniently support both docker on local machines and shifter at nersc. One way of setting this up is to provide the container environment in the definition of the `site`, then all the apps running on that site will run in that container. For nersc, to handle `shifter`, it sounds like all we need is to setup the `site` with a slurm script header which provides the shifter parameters (like which image to use). So this is technically doable :-) .

Here is a proposal for how containers could be used in the `ceci` framework:
We could ask that every `ceci` module, like `TXpipe`, provide a Dockerfile which can be used to execute all the stages defined in that module. That Dockerfile should extend a given base file, that would be common to all modules, for instance a given version of the LSST stack.

This way, we can reuse the same `site` to run various stages in parallel when we can. When combining different `ceci` modules, like photoz, shape measurement, and txpipe, each module will have their own docker image, and since they are all based on the same base, we can hope that one could still install the complete environment locally if they needed to.

@joezuntz let me know if that sounds good to you or if you anticipate more complicated patterns where this would fail.

**Comment by joezuntz** [comment]
I think this is a great idea overall and necessary.

Two quick thoughts 

- I think this should be optional - the default behaviour should still be to run directly.

- I can just about envisage a situation where we might want different containers for different stages in the same pipeline, particularly when we start combining pipelines.

- Should we be specifying containers in the code or in the config?

If we want to specify this in the configuration, as opposed to the code, then in terms of UI this (both) could be done by having an optional setting:
```
container: user_name/container_name
```
in the yaml file, which would set a default container to be used, and then in each `stages` entry potentially override it.

alternatively we could do:
```
containers:
    txpipe: user_name/container_name
    other_module: another_user_name/another_container_name
```

**Comment by joezuntz** [comment]
Containers (shifter &  docker) are supported cleanly in 1.0
