### ISSUE TITLE
Breakage from the new Parsl release

### ISSUE THREAD

**Issue by yadudoc** [LSSTDESC/ceci#13]
We just released the new Parsl v0.6.1 which has a few non-backward changes, that I suspect requires some updates in Ceci. Most changes will go to the launchers module. As a solution for the immediate problem I would recommend adding a specific requirement for an older parsl release, and add a separate PR for updated configs.

**Comment by joezuntz** [comment]
We did the temporary step for this yesterday - would be good to look at the next stages soon as I think they will be helpful.  @yadudoc would you be able to look at this?

The current launch equipment is all in the `parsl/sites` module.  It builds up a dictionary of sites by looping through all the stages and checking how many nodes each needs.  It also tells each stage which site it should use.

It looks like there may be a better way of doing this now, as there seems to be no concept of sites any more - is that right?  I can't quite see how we would have a workflow where different apps need different numbers of nodes - how would we do that?

**Comment by yadudoc** [comment]
Sure, I can do this one. We changed terminology but the concepts remain the same. What we called `sites` before did not necessarily map to a site (Cori / Theta) but rather a homogeneous pool of resources, so we now call it an `executor`.

For each `executor`, you could set `max_blocks=N, nodes_per_block=1` to set limits based on the stages that are going to the executor. Alternatively you could set `max_blocks` to a large number, and have Parsl take care of the scaling. 

As for apps with different needs, we could always create an `executor` for each kind and have the apps be directed to that `executor`. Different `executors` could support different `nodes_per_block`, container images, etc. Do the stages currently specify these requirements in some fashion ? If so, I can do translation to the new config definitions.

**Comment by joezuntz** [comment]
Ah, great - that does make more sense.

Yep, each stage includes a dictionary containing "nodes" (default=1) and "nprocess" (default=1).  Nodes is the number of nodes it needs, and nprocess the number of processes to tell mpirun or srun to use.

Right now I've been assuming that the minimum task size is 1 node, but we might change that in future.

**Comment by joezuntz** [comment]
Updated to parsl 0.0.8
