### ISSUE TITLE
Install Fails because of lack of requirements.txt

### ISSUE THREAD

**Issue by cavestruz** [LSSTDESC/ceci#17]
So, ceci is installed in nersc, so [we](https://github.com/LSSTDESC/CLMM/issues/46) should be okay for hack week, but I wanted to test out installing ceci locally.  
I've done the following:

(1) python (or python3) setup.py install (instructions on the read the docs) gives an error
Running parsl-0.5.2/setup.py -q bdist_egg --dist-dir /tmp/easy_install-dufhqeco/parsl-0.5.2/egg-dist-tmp-kzi8121i
error: [Errno 2] No such file or directory: 'requirements.txt'

(2) Also, if I pip install git+git://github.com/EiffL/python-cwlgen.git  (instructions on the ceci readme), I	 get
ceci 0.0.5 requires parsl<0.6.0, which is not installed.

(2) After I pip install parsl, I get:
cwlgen 0.2.6 has requirement ruamel.yaml==0.13.13, but you'll have ruamel-yaml -VERSION which is incompatible.
ceci 0.0.5 has requirement parsl<0.6.0, but you'll have parsl 0.6.1 which is incompatible.

- The error message from (2) looks related to #13 and #15 
- For the error message from (1), is there a requirements.txt file elsewhere for me to include in the installation, or should there be a flag to not?

**Comment by joezuntz** [comment]
Fixed in 1.0
