### ISSUE TITLE
Error running test/test.yml due to lack of full path log file name.

### ISSUE THREAD

**Issue by cwwalter** [LSSTDESC/ceci#26]
Doing some testing running 'ceci ./test/test.yml` I was getting:

```
  File "/Users/walter/.conda/envs/3x2pt/lib/python3.8/site-packages/ceci/main.py", line 37, in run
    os.makedirs(os.path.split(log_file)[0], exist_ok=True)
  File "/Users/walter/.conda/envs/3x2pt/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''
``` 

This is because test.yml contains 

```
# Put the log for the overall pipeline infrastructure in this file:
pipeline_log: log.txt
```

changing to './log.txt' fixes the error. But, the parser should probably be more robust.

**Comment by joezuntz** [comment]
Hi Chris - thanks! Which branch is this?  As soon as @rmjarvis have finished his review I'd like to merge to the v1.0 branch, which make some changes.

**Comment by cwwalter** [comment]
master.

**Comment by cwwalter** [comment]
OK, see in the v1.0 branch at least the text in the yaml file does have the path.

**Comment by joezuntz** [comment]
This is no longer relevant in 1.0
