### ISSUE TITLE
Handle parameters that are 'None' in  stage configuraitons in set_config.

### ISSUE THREAD

**Issue by eacharles** [LSSTDESC/ceci#67]
As it is now, if the default for a configuration parameter is not set (i.e., `None`) and the user tries to set it to `None` the code thinks that is has a missing parameter.  

We need a way to distinguish this.   As some level the issue is that the mechanism of definition of configuration parameters through config_options class data doesn't distinguish these cases.

**Comment by joezuntz** [comment]
Closed by #73
