### ISSUE TITLE
PipelineStage.open_input and PipelineStage.open_output don't work with aliases

### ISSUE THREAD

**Issue by joezuntz** [LSSTDESC/ceci#71]
The `open_input` method currently fails when you have an alias defined, whether you call it with the original tag or the alias.

One of them fails on get_input_type and the other on just get_input.

Something similar happens with open_output.

**Comment by joezuntz** [comment]
Test in this branch: `open-input-bug`

**Comment by eacharles** [comment]
is this fixed?

**Comment by joezuntz** [comment]
Yep, I think so!
