### ISSUE TITLE
Printing Parameter descriptions in help()

### ISSUE THREAD

**Issue by jfcrenshaw** [LSSTDESC/ceci#94]
If I have a stage, and call `help(stage)` to look at the docstring, it just looks like this

```python
config_options = {'param1': <ceci.config.StageParameter object>,...
```

It would be great if it would print something like

```python
- param1: type, default=...
      param1 is the...
```

**Comment by alice-crafford** [comment]
Yes I had this issue too, here's a specific example:

https://rail-hub.readthedocs.io/en/stable/api/rail.estimation.algos.pzflow_nf.html#rail.estimation.algos.pzflow_nf.PZFlowInformer 

The config options as they are here are a bit difficult to understand, @jfcrenshaw 's idea would be very helpful!

**Comment by joezuntz** [comment]
I have a proposed fix for this in #98  - could either one of you (@jfcrenshaw or @alice-crafford ) have a look at this and see what you think?

**Comment by jfcrenshaw** [comment]
It looks good to me!

**Comment by joezuntz** [comment]
Version 1.15 includes this change and is on its way to pypi.
